# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: build and push ui
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DockerhubUsername }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DockerhubPassword }}
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: docker.io
        # Docker repository to tag the image with
        repository: covid-prediction-ui
#         # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
#         tags: master
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true
        # Path to the build context
        path: frontend
        # Whether to push the image
        push: true
    - name: build and push api
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DockerhubUsername }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DockerhubPassword }}
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: docker.io
        # Docker repository to tag the image with
        repository: covid-prediction-api
#         # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
#         tags: master
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true
        # Path to the build context
        path: backend
        # Whether to push the image
        push: true
